### ISSUE TITLE
Favicon / Logo

### ISSUE THREAD

**Issue by danrschlosser** [CampusData/campusdata.github.io#11]
We need a logo / something for our Twitter bio / something for the favicon

**Comment by hydrosquall** [comment]
Made favicon out of the existing campusdata logo and included in it this commit: https://github.com/hydrosquall/campusdata.github.io/commit/5fe081831c806ac3049b52e15f9a1a70920de614

If you add me to the CampusData organization, I can fork within the site project rather than merging over from a random fork over on my own account.
